
export interface Product {
  id: string;
  name: string;
  brand: string;
  price: number;
  stock: number;
  category: string;
  imageUrl: string;
  shippingCost: number;
}

export interface CartItem extends Product {
  quantity: number;
}

export interface Order {
  id: string;
  customerName: string;
  customerPhone: string;
  items: CartItem[];
  totalPrice: number; // Grand total (items + shipping)
  totalShipping: number;
  date: string;
  aiSummary?: string; // Generated by Gemini
  isLoadingAi?: boolean;
  synced?: boolean; // True if saved to cloud
}

export type ViewState = 'shop' | 'history';
